name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: \${{ secrets.DOCKER_USERNAME }}
        password: \${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t \${{ secrets.DOCKER_USERNAME }}/spring-boot-hello-world .
        docker push \${{ secrets.DOCKER_USERNAME }}/spring-boot-hello-world

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: YOUR_AWS_REGION

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name YOUR_EKS_CLUSTER_NAME --region YOUR_AWS_REGION

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install hello-world-chart ./helm-chart --set image.repository=\${{ secrets.DOCKER_USERNAME }}/spring-boot-hello-world --set image.tag=latest
